"""empty message

Revision ID: f944c7c8e2af
Revises: e0344d977cc8
Create Date: 2022-06-04 18:06:34.826177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f944c7c8e2af'
down_revision = 'e0344d977cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'show_id')
    # ### end Alembic commands ###
